node {
   stage 'Checkout'
     git url: 'git@github.com:stelligent/pci-dss-infra.git'

   stage 'Commit'
     sh 'pipeline/run-static-analysis.sh'

   stage 'Acceptance'
     parallel 'create infrastructure': {
                sh 'pipeline/create-infrastructure.sh'
                sh 'pipeline/run-infrastructure-tests.sh'
              },

              //'update infrastructure': {
              //  sh 'pipeline/update-infrastructure.sh'
              //  sh 'pipeline/run-infrastructure-tests.sh'
              //},

              failFast: true

     sh 'pipeline/store-distros.sh'
}